const languageInformation = {
  en : {name: 'English', speaker: 'US English Female'},
  es : {name: 'Spanish', speaker: 'Spanish Female'},
  fr : {name: 'French', speaker: 'French Female'},
  de : {name: 'Deutsch', speaker: 'Deutsch Female'},
  it : {name: 'Italian', speaker: 'Italian Female'},
  el : {name: 'Greek', speaker: 'Greek Female'},
  hu : {name: 'Hungarian', speaker: 'Hungarian Female'},
  tr : {name: 'Turkish', speaker: 'Turkish Female'},
  ru : {name: 'Russian', speaker: 'Russian Female'},
  nl : {name: 'Dutch', speaker: 'Dutch Female'},
  sv : {name: 'Swedish', speaker: 'Swedish Female'},
  no : {name: 'Norwegian', speaker: 'Norwegian Female'},
  ja : {name: 'Japanese', speaker: 'Japanese Female'},
  ko : {name: 'Korean', speaker: 'Korean Female'},
  zh : {name: 'Chinese', speaker: 'Chinese Female'},
  hi : {name: 'Hindi', speaker: 'Hindi Female'},
  sr : {name: 'Serbian', speaker: 'Serbian Male'},
  hr : {name: 'Croatian', speaker: 'Croatian Male'},
  bs : {name: 'Bosnian', speaker: 'Bosnian Male'},
  ro : {name: 'Romanian', speaker: 'Romanian Male'},
  ca : {name: 'Catalan', speaker: 'Catalan Male'},
  fi : {name: 'Finnish', speaker: 'Finnish Female'},
  af : {name: 'Afrikaans', speaker: 'Afrikaans Male'},
  sq : {name: 'Albanian', speaker: 'Albanian Male'},
  ar : {name: 'Arabic', speaker: 'Arabic Male'},
  hy : {name: 'Armenian', speaker: 'Armenian Male'},
  cs : {name: 'Czech', speaker: 'Czech Female'},
  da : {name: 'Danish', speaker: 'Danish Female'},
  eo : {name: 'Esperanto', speaker: 'Esperanto Male'},
  if : {name: 'Icelandic', speaker: 'Icelandic Male'},
  id : {name: 'Indonesian', speaker: 'Indonesian Female'},
  la : {name: 'Latin', speaker: 'Latin Female'},
  lv : {name: 'Latvian', speaker: 'Latvian Male'},
  mk : {name: 'Macedonian', speaker: 'Macedonian Male'},
  pl : {name: 'Polish', speaker: 'Polish Female'},
  pt : {name: 'Portuguese', speaker: 'Portuguese Female'},
  sk : {name: 'Slovak', speaker: 'Slovak Female'},
  sw : {name: 'Swahili', speaker: 'Swahili Male'},
  ta : {name: 'Tamil', speaker: 'Tamil Male'},
  th : {name: 'Thai', speaker: 'Thai Female'},
  vi : {name: 'Vietnamese', speaker: 'Vietnamese Male'},
  cy : {name: 'Welsh', speaker: 'Welsh Male'},
}

export default languageInformation;